VodafonNumbers/Models/Number.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodafonNumbers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Number()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public int ID { get; set; }
        public string No { get; set; }
        public Nullable<bool> IsChoosen { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public string UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}

VodafonNumbers/Models/NumbersViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Vodafon.Models
{
    public class NumbersViewModel
    {
        public int ID { get; set; }
        public string No { get; set; }
        public bool IsChoosen { get; set; }
        public bool IsPrivate { get; set; }
        public string UserID { get; set; }
    }
}

VodafonNumbers/Controllers/NumbersController.cs
using Microsoft.AspNet.Identity;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vodafon.Models;
using VodafonNumbers.Hubs;
using VodafonNumbers.Models;

namespace Vodafon.Controllers
{
    [Authorize]
    public class NumbersController : Controller
    {
        private VodafonEntities db = new VodafonEntities();
        private ApplicationDbContext DefualtDB = new ApplicationDbContext();

        //[Authorize]
        // GET: Numbers
        public ActionResult ImportNumbers()
        {

            return View("Index");
        }

        [HttpGet]
        public ActionResult Create()
        {

            var Numsads = db.Numbers.Where(a => a.IsChoosen == true && a.Sales.Count == 0).ToList();
            for (int i = 0; i < Numsads.Count; i++)
            {
                Numsads[i].IsChoosen = false;
            }
            if (Numsads.Count > 0)
                db.SaveChanges();



            var Nums = db.Numbers.Where(a => a.IsChoosen != true && a.Sales.Count > 0).ToList();
            foreach (var item in Nums)
            {
                if (item.Sales.FirstOrDefault().StatusID != 3)
                    item.IsChoosen = true;
            }

            if (Nums.Count > 0)
                db.SaveChanges();

            //for zeros
            var Numers = db.Numbers.ToList();
            foreach (var item in Numers)
            {
                string num = item.No;
                if(num[0] != '0')
                {
                    item.No = "0" + item.No;
                }
            }
            db.SaveChanges();

            NumbersHub.Show();
            var Numbers = db.Numbers.Where(a => a.IsChoosen != true && a.IsPrivate != true).ToList();

            string userId = User.Identity.GetUserId();
            var user = (new ApplicationDbContext()).Users.FirstOrDefault(s => s.Id == userId);
            var roles = DefualtDB.Roles.Where(a => a.Users.Any(x => x.UserId == userId)).ToList();
            if (roles.Count > 0)
            {
                ViewBag.UserRole = roles[0].Name;
            }
            return View(Numbers);
        }

        public ActionResult PrivateNumbers()
        {
            var Numbers = db.Numbers.Select(a => new NumbersViewModel
            {
                ID = a.ID,
                IsChoosen = a.IsChoosen ?? false,
                IsPrivate = a.IsPrivate ?? false,
                No = a.No
            }).ToList();

            // _model.Data = Numbers;

            return View(Numbers);
        }

        public int? GetNumberId(string number)
        {
            var Number = db.Numbers.Where(a => a.No.Contains(number)).FirstOrDefault();
            if (Number != null)
                return Number.ID;

            return null;
        }



        [HttpPost]
        public ActionResult PrivateNumbers(List<NumbersViewModel> modelList)
        {
            foreach (var item in modelList)
            {
                Number number = db.Numbers.Where(a => a.ID == item.ID).FirstOrDefault();
                number.IsChoosen = item.IsChoosen;
                number.IsPrivate = item.IsPrivate;
            }
            db.SaveChanges();

            return RedirectToAction("Create");
        }

        public ActionResult Choose(int Id)
        {
            string userId = User.Identity.GetUserId();
            var No = db.Numbers.Where(a => a.ID == Id).FirstOrDefault();
            if (No != null)
            {
                No.IsChoosen = true;
                No.UserID = userId;
                db.SaveChanges();
            }
            return RedirectToAction("Create", "Sales", new { numberID = No.ID });
        }

        public ActionResult UnChoose(int Id)
        {
            var No = db.Numbers.Where(a => a.ID == Id).FirstOrDefault();
            No.IsChoosen = false;
            db.SaveChanges();

            //NumbersHub.Show();
            //var Numbers = db.Numbers.Where(a => a.IsChoosen != true && a.IsPrivate != true).ToList();
            return View();
        }

        public ActionResult RemoveAll()
        {
            var No = db.Numbers.Where(a => a.Sales.Count == 0).ToList();
            db.Numbers.RemoveRange(No);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        public JsonResult Get()
        {

            using (var connection = new SqlConnection(ConfigurationManager.ConnectionStrings["VodafonConnection"].ConnectionString))
            {
                connection.Open();
                using (SqlCommand command = new SqlCommand(@"SELECT [ID],[No],[IsChoosen] FROM [dbo].[Numbers] WHERE [IsChoosen] <> 1 and [IsPrivate] <> 1", connection))
                {
                    // Make sure the command object does not already have
                    // a notification object associated with it.
                    command.Notification = null;

                    SqlDependency dependency = new SqlDependency(command);
                    dependency.OnChange += new OnChangeEventHandler(dependency_OnChange);

                    if (connection.State == ConnectionState.Closed)
                        connection.Open();

                    SqlDataReader reader = command.ExecuteReader();

                    var listCus = reader.Cast<IDataRecord>()
                            .Select(x => new
                            {
                                Id = (int)x["ID"],
                                No = (string)x["No"],
                                IsChoosen = (bool)x["IsChoosen"],
                            }).ToList();

                    return Json(new { listCus = listCus }, JsonRequestBehavior.AllowGet);

                }
            }
        }


        private void dependency_OnChange(object sender, SqlNotificationEventArgs e)
        {
            NumbersHub.Show();
        }


        public ActionResult Upload(FormCollection formCollection)
        {
            var numberList = new List<Number>();
            if (Request != null)
            {
                HttpPostedFileBase file = Request.Files["UploadedFile"];
                if ((file != null) && (file.ContentLength > 0) && !string.IsNullOrEmpty(file.FileName))
                {
                    string fileName = file.FileName;
                    string fileContentType = file.ContentType;
                    byte[] fileBytes = new byte[file.ContentLength];
                    var data = file.InputStream.Read(fileBytes, 0, Convert.ToInt32(file.ContentLength));
                    using (var package = new ExcelPackage(file.InputStream))
                    {
                        var currentSheet = package.Workbook.Worksheets;
                        var workSheet = currentSheet.First();
                        var noOfCol = workSheet.Dimension.End.Column;
                        var noOfRow = workSheet.Dimension.End.Row;
                        for (int rowIterator = 1; rowIterator <= noOfRow; rowIterator++)
                        {
                            var number = new Number();
                            number.No = workSheet.Cells[rowIterator, 1].Value.ToString();
                            number.IsChoosen = false;
                            number.IsPrivate = false;
                            numberList.Add(number);
                        }
                    }
                }
            }

            foreach (var item in numberList)
            {
                if(item.No != "Number")
                {
                    var num = db.Numbers.Where(a => a.No.Contains(item.No)).FirstOrDefault();
                    if (num == null)
                        db.Numbers.Add(item);
                }
               
            }

            db.SaveChanges();

            return RedirectToAction("Create");
        }


        public ActionResult CheckNumberIsValid(int? NumberId)
        {
            bool valid = true;
            string userId = User.Identity.GetUserId();
            var No = db.Numbers.Where(a => a.ID == NumberId).FirstOrDefault();
            if (No != null)
            {
                if (No.UserID != userId)
                    valid = !(No.IsChoosen) ?? true;
            }
            return Json(new { valid = valid }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ExportNumbers()
        {
            var Numbers = db.Numbers.Select(a => new NumbersViewModel
            {
                ID = a.ID,
                IsChoosen = a.IsChoosen ?? false,
                IsPrivate = a.IsPrivate ?? false,
                No = a.No
            }).ToList();

            return View("ExportPrivateNumbers", Numbers);
        }
        public ActionResult GetPrivateOnly(bool? privateOnly, bool? publicOnly)
        {
            List<NumbersViewModel> Numbers = new List<NumbersViewModel>();

            if (privateOnly == true)
            {
                Numbers = db.Numbers.Where(a => a.IsPrivate == true).Select(a => new NumbersViewModel
                {
                    ID = a.ID,
                    IsChoosen = a.IsChoosen ?? false,
                    IsPrivate = a.IsPrivate ?? false,
                    No = a.No
                }).ToList();
            }

            else if (publicOnly == true)
            {
                Numbers = db.Numbers.Where(a => a.IsPrivate != true && a.IsChoosen != true).Select(a => new NumbersViewModel
                {
                    ID = a.ID,
                    IsChoosen = a.IsChoosen ?? false,
                    IsPrivate = a.IsPrivate ?? false,
                    No = a.No
                }).ToList();
            }

            else
            {
                Numbers = db.Numbers.Select(a => new NumbersViewModel
                {
                    ID = a.ID,

VodafonNumbers/Views/Numbers/Create.cshtml
@model List<VodafonNumbers.Models.Number>

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
#outer
{
    width:100%;
    text-align: center;
}
.inner
{
    display: inline-block;
}
</style>

<br />
<br />
<div id="outer">
    <div class="inner"><button type="button" class="btn btn-primary" onclick="window.location.href = '/Sales/Create'" id="SaleBtn">Create Sale</button></div>
    @if (ViewBag.UserRole != "Agent")
    {
        <div class="inner"><button type="button" class="btn btn-primary" onclick="window.location.href = '/Numbers/ImportNumbers'" id="SaleBtn">Import Numbers</button></div>
        <div class="inner"><button type="button" class="btn btn-primary" onclick="window.location.href = '/Numbers/PrivateNumbers'" >Private Numbers</button></div>
        <div class="inner"><button type="button" class="btn btn-danger" onclick="window.location.href = '/Numbers/RemoveAll'">Remove All Numbers</button></div>
        <div class="inner"><button type="button" class="btn btn-success" onclick="window.location.href = '/Numbers/ExportNumbers'">Export Numbers</button></div>
    }
   
</div>
@*<button type="button" class="btn btn-primary" onclick="window.location.href = '/Sales/Create'" id="SaleBtn">Create Sale</button>*@
<br />

@Html.Hidden("Get", Url.Action("Get", "Numbers"))

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <table class="table">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Number
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="tblInfo">

            </tbody>

                @*@for (int i = 0; i < Model.Count; i++)
                {
                    <tr>
                        <td>
                            @(i + 1)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => Model[i].No)
                        </td>
                        <td>
                            @Html.ActionLink("Choose", "Edit", new { id = Model[i].ID })
                        </td>
                    </tr>
                }*@

        </table>

    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VodafonNumbers/Views/Numbers/ExportPrivateNumbers.cshtml
@model List<Vodafon.Models.NumbersViewModel>

@{
    ViewBag.Title = "PrivateNumbers";
}

<h2>Private Numbers</h2>

<div class="form-group row">
    <div class="col-md-4">
        @Html.CheckBox("private", false, new { id = "privateOnly" })
        @Html.Label("Show Private only")
    </div>
    <div class="col-md-4">
        @Html.CheckBox("public", false, new { id = "publicOnly" })
        @Html.Label("Show public only")
    </div>
    @*<div class="col-md-4">
        <input type="button" value="OK" class="btn btn-primary" onclick="GetData()" />
    </div>*@
</div>


<div class="row GridDiv">
    @Html.Partial("_ExportPrivateNumbers", Model)
</div>

<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<script>
    $(document).ready(function () {

        $('#privateOnly').change(function () {
            RunsOnMondays();
        });

        $('#publicOnly').change(function () {
            RunsOnSundays();
        });

    });

    function RunsOnMondays() {
        if ($('#privateOnly').prop('checked')) {
            $.ajax({
                url: "/Numbers/GetPrivateOnly",
                type: 'get',
                data: { privateOnly: true, publicOnly: false },
                success: function (result) {
                    debugger;
                    $(".GridDiv").empty();
                    $(".GridDiv").html(result);
                }
            });
        } else {
            $.ajax({
                url: "/Numbers/GetPrivateOnly",
                type: 'get',
                data: { privateOnly: false, publicOnly: false },
                success: function (result) {
                    debugger;
                    $(".GridDiv").empty();
                    $(".GridDiv").html(result);
                }
            });
        }
    }

    function RunsOnSundays() {
        if ($('#publicOnly').prop('checked')) {
            $.ajax({
                url: "/Numbers/GetPrivateOnly",
                type: 'get',
                data: { privateOnly: false, publicOnly: true },
                success: function (result) {
                    debugger;
                    $(".GridDiv").empty();
                    $(".GridDiv").html(result);
                }
            });
        } else {
            $.ajax({
                url: "/Numbers/GetPrivateOnly",
                type: 'get',
                data: { privateOnly: false, publicOnly: false },
                success: function (result) {
                    debugger;
                    $(".GridDiv").empty();
                    $(".GridDiv").html(result);
                }
            });
        }
    }

        function GetData() {
            debugger;
            var privateOnly = false;
            var publicOnly = false;
            if ($('#privateOnly').is(":checked")) {
                privateOnly = true;
            }
            if ($('#publicOnly').is(":checked")) {
                publicOnly = true;
            }           
                $.ajax({
                    url: "/Numbers/GetPrivateOnly",
                    type: 'get',
                    data: { privateOnly: privateOnly, publicOnly: publicOnly },
                    success: function (result) {
                        debugger;
                        $(".GridDiv").empty();
                        $(".GridDiv").html(result);
                    }
                });
        }
</script>

VodafonNumbers/Views/Numbers/Index.cshtml
@using (Html.BeginForm("Upload", "Numbers", FormMethod.Post, new
{
    enctype = "multipart/form-data"
}))
{
    <br />
    <br />
    <table> 
    <tr> 
        <td> Choose Exel File: </td> 
        <td> <input type="file" name="UploadedFile" /> </td>
         </tr>

        <tr> <td></td>  </tr>
     <tr> 

        <td colspan="2"> 
         <input type="submit" name="Submit" value="Submit" /> 
         </td> 
        </tr> 
    </table>
} 

VodafonNumbers/Views/Numbers/PrivateNumbers.cshtml
@model List<Vodafon.Models.NumbersViewModel>

@{
    ViewBag.Title = "PrivateNumbers";
}

<h2>PrivateNumbers</h2>
@using (Html.BeginForm())
{
    <table class="table">
        <tr>
            <th>Number</th>
            <th>Is Choosen</th>
            <th>Is Private</th>
        </tr>
        @{
            for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(modelItem => Model[i].ID)
                        @Html.DisplayFor(modelItem => Model[i].No)
                    </td>
                    <td>
                        @Html.CheckBoxFor(modelItem => Model[i].IsChoosen, new { htmlAttributes = new { @class = "form-control" } })
                        @*@Html.DisplayFor(modelItem => item.IsChoosen)*@
                    </td>
                    <td>
                        @Html.CheckBoxFor(modelItem => Model[i].IsPrivate, new { htmlAttributes = new { @class = "form-control" } })
                        @*@Html.DisplayFor(modelItem => item.IsPrivate)*@
                    </td>
                </tr>
            }
        }
    </table>


    @*<table class="table">
        <tr>
            <th>
                @Html.DisplayName("Number")
            </th>
            <th>
                @Html.DisplayName("Choosen")
            </th>
            <th>
                @Html.DisplayName("Private")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Data)
        {
            <tr>
                <td>
                    @Html.HiddenFor(modelItem => item.ID)
                    @Html.DisplayFor(modelItem => item.No)
                </td>
                <td>
                    @Html.CheckBoxFor(modelItem => item.IsChoosen, new { htmlAttributes = new { @class = "form-control" } })
                </td>
                <td>
                    @Html.CheckBoxFor(modelItem => item.IsPrivate, new { htmlAttributes = new { @class = "form-control" } })
                </td>
            </tr>
        }

    </table>*@

    <div class="form-group row">
        <div class="col-md-offset-2 col-md-1">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

VodafonNumbers/Views/Numbers/UnChoose.cshtml
@model List<VodafonNumbers.Models.Number>

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<br />
<br />
<button type="button" class="btn btn-primary" onclick="window.location.href = '/Sales/Create'" id="SaleBtn">Create Sale</button>
<br />*@

<h2 style="text-align:center"> Sale Cancled Successfully </h2>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VodafonNumbers/Views/Numbers/_ExportPrivateNumbers.cshtml
@model List<Vodafon.Models.NumbersViewModel>

@{
    ViewBag.Title = "PrivateNumbers";
}

@using (Html.BeginForm("ExportToExcel", "Numbers", FormMethod.Post))
{
    <table class="table">
        <tr>
            <th>Number</th>
            <th>Is Choosen</th>
            <th>Is Private</th>
        </tr>
        @{
            for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(modelItem => Model[i].ID)
                        @Html.HiddenFor(modelItem => Model[i].No)
                        @Html.DisplayFor(modelItem => Model[i].No)
                    </td>
                    <td>
                        @Html.CheckBoxFor(modelItem => Model[i].IsChoosen, new { htmlAttributes = new { @class = "form-control" } })
                        @*@Html.DisplayFor(modelItem => item.IsChoosen)*@
                    </td>
                    <td>
                        @Html.CheckBoxFor(modelItem => Model[i].IsPrivate, new { htmlAttributes = new { @class = "form-control" } })
                        @*@Html.DisplayFor(modelItem => item.IsPrivate)*@
                    </td>
                </tr>
            }
        }
    </table>


    <div class="form-group row">
        <div class="col-md-offset-2 col-md-1">
            <input type="submit" value="Export Excel" class="btn btn-primary" />
        </div>
    </div>
            }