VodafonNumbers/Models/Sale.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VodafonNumbers.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public long Serial { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> ChoosenNo { get; set; }
        public Nullable<int> Package { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string CustomerID { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
    
        public virtual Number Number { get; set; }
        public virtual Package Package1 { get; set; }
        public virtual Status Status { get; set; }
    }
}

VodafonNumbers/Models/SalesViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using VodafonNumbers.Models;

namespace Vodafon.Models
{
    public class SalesViewModel
    {
        public int ID { get; set; }
        public long Serial { get; set; }
        public string CustomerName { get; set; }
       // [Required]
        public Nullable<int> ChoosenNo { get; set; }
        public string ChoosenNumber { get; set; }
       // [Required]
        public Nullable<int> Package { get; set; }
        public string PackageName { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string StatusName { get; set; }
        public int? StatusID { get; set; }
        public string CustomerID { get; set; }
        public string Comment { get; set; }

        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string CreationDateString { get; set; }
        public string VisitDateString { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public string ActivationDateString { get; set; }

        public static SalesViewModel GetVMFromDB(Sale _obj)
        {
            SalesViewModel model = new SalesViewModel();
            if (_obj != null)
            {
                model.ID = _obj.ID;
                model.Serial = _obj.Serial;
                model.CustomerName = _obj.CustomerName;
                model.CustomerID = _obj.CustomerID;
                model.ChoosenNo = _obj.ChoosenNo;
                model.ChoosenNumber = _obj.Number != null ? _obj.Number.No : "";;
                model.Package = _obj.Package;
                model.PackageName = _obj.Package != null ? _obj.Package1.PackageName : "";
                model.Mobile1 = _obj.Mobile1;
                model.Mobile2 = _obj.Mobile2;
                model.Address = _obj.Address;
                model.District = _obj.District;
                model.City = _obj.City;
                model.StatusID = _obj.StatusID;
                model.UserID = _obj.UserID;
                model.StatusName = _obj.Status != null ? _obj.Status.Name : "";
                model.UserName = _obj.UserName;
                model.Comment = _obj.Comment;
                model.CreationDate = _obj.CreationDate;
                model.CreationDateString = _obj.CreationDate != null ? _obj.CreationDate.Value.ToString("dd/MM/yyyy") : "";
                model.VisitDate = _obj.VisitDate;
                model.VisitDateString = _obj.VisitDate != null ? _obj.VisitDate.Value.ToString("dd/MM/yyyy") : "";
                model.ActivationDate = _obj.ActivationDate;
                model.ActivationDateString = _obj.ActivationDate != null ? _obj.ActivationDate.Value.ToString("dd/MM/yyyy") : "";
            }
               
            return model;
        }

        public static Sale GetDBFromVM(SalesViewModel sale)
        {
            Sale obj = new Sale();
            if (sale != null)
            {
                obj.Serial = sale.Serial;
                obj.Address = sale.Address;
                obj.ChoosenNo = sale.ChoosenNo;
                obj.City = sale.City;
                obj.CreationDate = DateTime.Now;
                obj.CustomerName = sale.CustomerName;
                obj.CustomerID = sale.CustomerID;
                obj.District = sale.District;
                obj.Mobile1 = sale.Mobile1;
                obj.Mobile2 = sale.Mobile2;
                obj.Mobile2 = sale.Mobile2;
                obj.Package = sale.Package;
                obj.StatusID = sale.StatusID;
                obj.Comment = sale.Comment;
                obj.ActivationDate = sale.ActivationDate;
            }           

            return obj;
        }

    }
}

VodafonNumbers/Controllers/SalesController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Vodafon.Models;
using VodafonNumbers.Models;
using Microsoft.AspNet.Identity.Owin;
using OfficeOpenXml;

namespace VodafonNumbers.Controllers
{
    [Authorize]
    public class SalesController : Controller
    {
        private VodafonEntities db = new VodafonEntities();
        private ApplicationDbContext DefualtDB = new ApplicationDbContext();

        // GET: Sales
        public ActionResult Index()
        {
             ViewBag.State = "Pending";
            List<SalesViewModel> sales = new List<SalesViewModel>();
            List<Sale> salesDB = new List<Sale>();
            string userId = User.Identity.GetUserId();
            var roles = DefualtDB.Roles.Where(a => a.Users.Any(x => x.UserId == userId)).ToList();
            if(roles.Count > 0)
            {
                Session["UserRole"] = roles[0].Name;
                //ViewBag.UserRole = roles[0].Name;

                if (roles[0].Name == "Agent")
                {
                    salesDB = db.Sales.ToList().Where(a => a.UserID == userId && a.StatusID == 4).OrderByDescending(s => s.ID).ToList();
                    foreach (var item in salesDB)
                    {
                        sales.Add(SalesViewModel.GetVMFromDB(item));
                    }

                }


                else
                {
                    salesDB = db.Sales.Where(a=> a.StatusID == 4).OrderByDescending(s => s.ID).ToList();
                    foreach (var item in salesDB)
                    {
                        sales.Add(SalesViewModel.GetVMFromDB(item));
                    }
                }
                          
            }

            var data = new[]{
                 new SelectListItem{ Value="1",Text="Serial"},
                 new SelectListItem{ Value="2",Text="ChoosenNo"},
                 new SelectListItem{ Value="3",Text="CustomerName"},
             };

            ViewBag.SearchTypes = data;

            return View(sales);
        }

        public ActionResult ActiveIndex()
        {
            ViewBag.State = "Active";
            List<Sale> salesDB = new List<Sale>();
            List<SalesViewModel> sales = new List<SalesViewModel>();
            string userId = User.Identity.GetUserId();
            var user = (new ApplicationDbContext()).Users.FirstOrDefault(s => s.Id == userId);
            Session["UserName"] = user.UserName;
            Session["UserId"] = user.Id;
            var roles = DefualtDB.Roles.Where(a => a.Users.Any(x => x.UserId == userId)).ToList();
            if (roles.Count > 0)
            {
                if (roles[0].Name == "Agent")
                {
                    salesDB = db.Sales.Where(a => a.UserID == userId && a.StatusID == 2).OrderByDescending(s => s.ID).ToList();
                    foreach (var item in salesDB)
                    {
                        sales.Add(SalesViewModel.GetVMFromDB(item));
                    }

                }


                else
                {
                    salesDB = db.Sales.Where(a => a.StatusID == 2).OrderByDescending(s => s.ID).ToList();
                    foreach (var item in salesDB)
                    {
                        sales.Add(SalesViewModel.GetVMFromDB(item));
                    }
                }
            }

            var data = new[]{
                 new SelectListItem{ Value="1",Text="Serial"},
                 new SelectListItem{ Value="2",Text="ChoosenNo"},
                 new SelectListItem{ Value="3",Text="CustomerName"},
             };

            ViewBag.SearchTypes = data;

            return View("Index" , sales);
        }

        public ActionResult FollowIndex()
        {
            ViewBag.State = "Follow";

            List<Sale> salesDB = new List<Sale>();
            List<SalesViewModel> sales = new List<SalesViewModel>();
            string userId = User.Identity.GetUserId();
            var roles = DefualtDB.Roles.Where(a => a.Users.Any(x => x.UserId == userId)).ToList();
            if (roles.Count > 0)
            {
                Session["UserRole"] = roles[0].Name;

                if (roles[0].Name == "Agent")
                {
                    salesDB = db.Sales.ToList().Where(a => a.UserID == userId && a.StatusID == 1).OrderByDescending(s => s.ID).ToList();
                    foreach (var item in salesDB)
                    {
                        sales.Add(SalesViewModel.GetVMFromDB(item));
                    }

                }


                else
                {
                    salesDB = db.Sales.Where(a => a.StatusID == 1).OrderByDescending(s => s.ID).ToList();
                    foreach (var item in salesDB)
                    {
                        sales.Add(SalesViewModel.GetVMFromDB(item));
                    }
                }
            }

            var data = new[]{
                 new SelectListItem{ Value="1",Text="Serial"},
                 new SelectListItem{ Value="2",Text="ChoosenNo"},
                 new SelectListItem{ Value="3",Text="CustomerName"},
             };

            ViewBag.SearchTypes = data;

            return View("Index", sales);
        }

        public ActionResult RejectIndex()
        {
            ViewBag.State = "Reject";

            List<Sale> salesDB = new List<Sale>();
            List<SalesViewModel> sales = new List<SalesViewModel>();
            string userId = User.Identity.GetUserId();
            var user = (new ApplicationDbContext()).Users.FirstOrDefault(s => s.Id == userId);
            Session["UserName"] = user.UserName;
            Session["UserId"] = user.Id;
            var roles = DefualtDB.Roles.Where(a => a.Users.Any(x => x.UserId == userId)).ToList();
            if (roles[0].Name == "Agent")
            {
                salesDB = db.Sales.ToList().Where(a => a.UserID == userId && a.StatusID == 3).OrderByDescending(s => s.ID).ToList();
                foreach (var item in salesDB)
                {
                    sales.Add(SalesViewModel.GetVMFromDB(item));
                }

            }


            else
            {
                salesDB = db.Sales.Where(a =>a.StatusID == 3).OrderByDescending(s => s.ID).ToList();
                foreach (var item in salesDB)
                {
                    sales.Add(SalesViewModel.GetVMFromDB(item));
                }
            }

            var data = new[]{
                 new SelectListItem{ Value="1",Text="Serial"},
                 new SelectListItem{ Value="2",Text="ChoosenNo"},
                 new SelectListItem{ Value="3",Text="CustomerName"},
             };

            ViewBag.SearchTypes = data;

            return View("Index", sales);
        }

        // GET: Sales/Create
        public ActionResult Create(int? numberID)
        {
            var Number = db.Numbers.Where(a => a.ID == numberID).FirstOrDefault();

            SalesViewModel _model = new SalesViewModel();

            List<Sale> SalesList = db.Sales.ToList();
            if (SalesList.Count == 0)
                _model.Serial = 1;

            else
                _model.Serial = SalesList.Max(m => m.Serial) + 1;
            _model.ChoosenNo = numberID;

            var ChoosenNumbers = db.Numbers.Where(a => a.ID == numberID).ToList();

            ViewBag.ChoosenNumbers = db.Numbers.Where(a=>a.IsChoosen != true && a.IsPrivate != true).Select(m => new SelectListItem
            {
                Value = m.ID.ToString(),
                Text = m.No,
            }).ToList();


            ViewBag.Packages = db.Packages.Select(m => new SelectListItem
            {
                Value = m.ID.ToString(),
                Text = m.PackageName,
            }).ToList();

            ViewBag.Status = db.Status.Select(m => new SelectListItem
            {
                Value = m.ID.ToString(),
                Text = m.Name,
            }).ToList();


            string userId = User.Identity.GetUserId();
            if (Number != null)
            {
                Number.IsChoosen = true;
                Number.UserID = userId;
                db.SaveChanges();
                //_model.ChoosenNo = Number.No;
            }

            return View(_model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SalesViewModel sale)
        {
            //for number
            var No = db.Numbers.Where(a => a.ID == sale.ChoosenNo).FirstOrDefault();
            if(No != null)
            {
                No.IsChoosen = true;
                db.SaveChanges();
            }
           
            string userId = User.Identity.GetUserId();
            var user = (new ApplicationDbContext()).Users.FirstOrDefault(s => s.Id == userId);
            Session["UserName"] = user.UserName;
            Session["UserId"] = user.Id;

            if (ModelState.IsValid)
            {
                Sale obj = new Sale();

                List<Sale> SalesList = db.Sales.ToList();
                if (SalesList.Count == 0)
                    obj.Serial = 1;

                else
                    obj.Serial = SalesList.Max(m => m.Serial) + 1;

                //obj.Serial = sale.Serial;
                obj.Address = sale.Address;
                obj.ChoosenNo = sale.ChoosenNo;
                obj.City = sale.City;
                obj.CreationDate = DateTime.Now;
                obj.CustomerID = sale.CustomerID;
                obj.CustomerName = sale.CustomerName;
                obj.District = sale.District;
                obj.Mobile1 = sale.Mobile1;
                obj.Mobile2 = sale.Mobile2;
                obj.Mobile2 = sale.Mobile2;
                obj.Package = sale.Package;
                obj.StatusID = sale.StatusID;
                obj.UserID = Session["UserId"].ToString();

VodafonNumbers/Views/Sales/Create.cshtml
@model Vodafon.Models.SalesViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Sale</h2>

@*<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@

@using (Html.BeginForm("Create", "Sales", FormMethod.Post,new { id = "CreateForm" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Serial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.HiddenFor(model => model.StatusID, new { id = "StatusID" })
                @Html.EditorFor(model => model.Serial, new { htmlAttributes = new { @class = "form-control" , id= "Serial", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.Serial, "", new { @class = "text-danger"  })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Customer ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ChoosenNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.ChoosenNo, new SelectList(ViewBag.ChoosenNumbers, "Value", "Text"), "-- Select Number --", new { @class = "form-control" , id= "ChoosenNoID" })                
                @Html.ValidationMessageFor(model => model.ChoosenNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Package, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Package, new SelectList(ViewBag.Packages, "Value", "Text"), "-- Select Package --", new { @class = "form-control" })
                @*@Html.EditorFor(model => model.Package, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.ValidationMessageFor(model => model.Package, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.District, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.District, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.District, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VisitDate , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
            @*    @Html.HiddenFor(model => model.VisitDateString, new { id = "VisitDateString" })*@
                @Html.EditorFor(model => model.VisitDate, new { htmlAttributes = new { @class = "form-control date-picker" , id = "VisitDate" } })
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-4">
                <button type="submit" class="btn btn-mini" id="SaveBTN" style="display: none;"></button>
            </div>
            <div class="col-md-1">
                <input type="button" value="Create" class="btn btn-success" id="CreateBTN" />
            </div>
            <div class="col-md-1">
                <input type="button" value="Follow" class="btn btn-primary" id="Follow" />
            </div>
            <div class="col-md-1">
                <input type="button" onclick="window.location.href = '/Numbers/UnChoose/@Model.ChoosenNo'"  value="Cancle" class="btn btn-danger" id="Cancle" />
            </div>
        </div>

    </div>
}

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@section scripts{

@Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>
        $(function () {
            $('.date-picker').datepicker({
                dateFormat: "mm/dd/yy"
            });
        })
    </script>

<script>

    //$('#VisitDate').change(function () {
    //    debugger
    //    var x = this.value;
    //    $('#VisitDateString').val(x);
    //})

    $("#Follow").click(function () {
        debugger
        $("#Follow").attr("disabled", true);
        $("#CreateBTN").attr("disabled", true);
        $("#Cancle").attr("disabled", true);
        $("#StatusID").val(1);
        //$("#CreateBTN").click(); // Submit the form

        var Serial = $("#Serial").val();
        $.ajax({
            url: "/Sales/CheckSerialIsValid",
            type: "POST",
            dataType: "json",
            success: function (data) {
                debugger
                if (data.validSerial != Serial) {
                    alert("This Serial will be changed to : " + data.validSerial)
                    Serial = parseInt(Serial);
                    $("#Serial").val((Serial + 1));
                }
            }
        });


        var NumberId = parseInt($("#ChoosenNoID").val());
        $.ajax({
            url: "/Numbers/CheckNumberIsValid",
            type: "POST",
            dataType: "json",
            data: { NumberId: NumberId },
            success: function (data) {
                debugger
                console.log(data);
                if (data.valid == true) {
                    $("#SaveBTN").click();
                }
                else {
                    alert("Please choose Anthor Number This One Choosed!!")
                    e.preventDefault();
                    return
                }
            }
        });

    });

    $("#CreateBTN").click(function (e) {
        debugger
        var Serial = $("#Serial").val();
        $.ajax({
            url: "/Sales/CheckSerialIsValid",
            type: "POST",
            dataType: "json",
            success: function (data) {
                debugger
                if (data.validSerial != Serial) {
                    alert("This Serial will be changed to : " + data.validSerial)
                    Serial = parseInt(Serial);
                    $("#Serial").val((Serial+1));
                }
            }
        });


       var NumberId = parseInt($("#ChoosenNoID").val());
        $.ajax({
            url: "/Numbers/CheckNumberIsValid",
            type: "POST",
            dataType: "json",
            data: { NumberId: NumberId },
            success: function (data) {
                debugger
                console.log(data);
                if (data.valid == true) {
                    $("#SaveBTN").click();
                }
                else {
                    alert("Please choose Anthor Number This One Choosed!!")
                    e.preventDefault();
                    return
                }
            }
        });
    });


</script>
}

VodafonNumbers/Views/Sales/NewIndex.cshtml
@model List<Vodafon.Models.SalesViewModel>

@{
    ViewBag.Title = "Index";
}


<br />
<br />
<script src="~/Scripts/jquery-1.12.4.min.js"></script>
<link href="~/Scripts/paging/jquery.dataTables.min.css" rel="stylesheet" />
<script src="~/Scripts/paging/jquery.dataTables.min.js"></script>

@using (Html.BeginForm("ExportToExcel", "Sales", FormMethod.Post))
{
    <table id="tbldata" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
        <tr>
            <th>Serial</th>
            <th>CustomerID</th>
            <th>CustomerName</th>
            <th>ChoosenNo</th>
            <th>Mobile1</th>
            <th>Mobile2</th>
            @*<th>Address</th>*@
            <th>City</th>
            <th>District</th>
            <th>UserName</th>
            <th>CreationDate</th>
            <th>Status</th>
            <th>Comment</th>
            <th></th>
        </tr>
        @{
            for (int i = 0; i < Model.Count; i++)
            {
                <tr>
                    <td>
                        @Html.HiddenFor(modelItem => Model[i].ID)
                        @Html.DisplayFor(modelItem => Model[i].Serial)
                        @Html.HiddenFor(modelItem => Model[i].Serial)
                        @Html.HiddenFor(modelItem => Model[i].PackageName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].CustomerID)
                        @Html.HiddenFor(modelItem => Model[i].CustomerID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].CustomerName)
                        @Html.HiddenFor(modelItem => Model[i].CustomerName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].ChoosenNumber)
                        @Html.HiddenFor(modelItem => Model[i].ChoosenNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Mobile1)
                        @Html.HiddenFor(modelItem => Model[i].Mobile1)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Mobile2)
                        @Html.HiddenFor(modelItem => Model[i].Mobile2)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => Model[i].Address)
                            @Html.HiddenFor(modelItem => Model[i].Address)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].City)
                        @Html.HiddenFor(modelItem => Model[i].City)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].District)
                        @Html.HiddenFor(modelItem => Model[i].District)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].UserName)
                        @Html.HiddenFor(modelItem => Model[i].UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].CreationDateString)
                        @Html.HiddenFor(modelItem => Model[i].CreationDateString)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].StatusName)
                        @Html.HiddenFor(modelItem => Model[i].StatusName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => Model[i].Address)
                        @Html.DisplayFor(modelItem => Model[i].Comment)
                        @Html.HiddenFor(modelItem => Model[i].Comment)
                    </td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { id = Model[i].ID })
                    </td>
                </tr>
            }
        }
    </table>


    <div class="form-group row">
        <div class="col-md-offset-2 col-md-1">
            <input type="submit" value="Export Excel" class="btn btn-primary" />
        </div>
    </div>
            }


<script>
 $(document).ready(function () {
     $('#tbldata').DataTable();
        });

</script>  